language: go

go:
  - 1.5
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - pip install --user codecov
script:
  - go test
  - $HOME/gopath/bin/goveralls -repotoken 9fQYRM6VveKxV1AF9nxJQswmrn0U9Zf4q
after_success:
  - codecov
