language: go

go:
  - 1.3
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover
script:
  - go test
  - $HOME/gopath/bin/goveralls -repotoken 9fQYRM6VveKxV1AF9nxJQswmrn0U9Zf4q
