language: go

os:
  - linux
  - osx

go:
  - 1.4.3
  - 1.5.4
  - 1.6.2
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - go test
  - $HOME/gopath/bin/goveralls -repotoken 9fQYRM6VveKxV1AF9nxJQswmrn0U9Zf4q
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
