language: go

go:
  - 1.5
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - pip install --user codecov
script:
  - go test
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
